const openBoardData = [
  {
    id: 1,
    board: "학업 게시판",
    title: "React 기초",
    author: "김철수",
    content: "React의 기본 개념을 설명합니다.",
    date: "2025-02-10",
    comment: 70,
    views: 100,
  },
  {
    id: 2,
    board: "취업 게시판",
    title: "Node.js 서버",
    author: "이영희",
    content: "Node.js 서버 설정 방법.",
    date: "2025-02-11",
    comment: 75,
    views: 85,
  },
  {
    id: 3,
    board: "프로젝트 게시판",
    title: "Python 데이터 분석",
    author: "박민수",
    content: "판다스를 활용한 데이터 분석.",
    date: "2025-02-12",
    comment: 100,
    views: 120,
  },
  {
    id: 4,
    board: "정보 게시판",
    title: "HTML & CSS",
    author: "정하나",
    content: "HTML과 CSS 기본 문법.",
    date: "2025-02-13",
    comment: 3,
    views: 90,
  },
  {
    id: 5,
    board: "학업 게시판",
    title: "알고리즘 문제 풀이",
    author: "손준호",
    content: "DFS와 BFS를 설명합니다.",
    date: "2025-02-14",
    comment: 10,
    views: 75,
  },
  {
    id: 6,
    board: "학업 게시판",
    title: "Java 기본",
    author: "김영수",
    content: "Java의 기본 개념을 다룹니다.",
    date: "2025-02-15",
    comment: 25,
    views: 110,
  },
  {
    id: 7,
    board: "취업 게시판",
    title: "면접 준비",
    author: "이진호",
    content: "개발자 면접 질문과 답변.",
    date: "2025-02-16",
    comment: 40,
    views: 95,
  },
  {
    id: 8,
    board: "프로젝트 게시판",
    title: "Django 웹 개발",
    author: "박지성",
    content: "Django 프레임워크 개요.",
    date: "2025-02-17",
    comment: 15,
    views: 80,
  },
  {
    id: 9,
    board: "정보 게시판",
    title: "Git 사용법",
    author: "정윤아",
    content: "Git 기본 사용법.",
    date: "2025-02-18",
    comment: 8,
    views: 60,
  },
  {
    id: 10,
    board: "학업 게시판",
    title: "자료구조 개념",
    author: "김민재",
    content: "스택과 큐 설명.",
    date: "2025-02-19",
    comment: 18,
    views: 85,
  },
  {
    id: 11,
    board: "취업 게시판",
    title: "포트폴리오 작성",
    author: "최서윤",
    content: "효과적인 포트폴리오 작성법.",
    date: "2025-02-20",
    comment: 55,
    views: 130,
  },
  {
    id: 12,
    board: "프로젝트 게시판",
    title: "Flask 웹 서비스",
    author: "윤석진",
    content: "Flask 기반 웹 서비스 개발.",
    date: "2025-02-21",
    comment: 20,
    views: 75,
  },
  {
    id: 13,
    board: "정보 게시판",
    title: "SQL 기본",
    author: "정은지",
    content: "SQL 기본 문법.",
    date: "2025-02-22",
    comment: 30,
    views: 90,
  },
  {
    id: 14,
    board: "학업 게시판",
    title: "운영체제 개념",
    author: "박성민",
    content: "운영체제의 기본 개념.",
    date: "2025-02-23",
    comment: 12,
    views: 78,
  },
  {
    id: 15,
    board: "취업 게시판",
    title: "이력서 작성",
    author: "조민지",
    content: "이력서 작성 팁.",
    date: "2025-02-24",
    comment: 22,
    views: 88,
  },
  {
    id: 16,
    board: "프로젝트 게시판",
    title: "Vue.js 시작하기",
    author: "김나현",
    content: "Vue.js의 기본 개념.",
    date: "2025-02-25",
    comment: 50,
    views: 105,
  },
  {
    id: 17,
    board: "정보 게시판",
    title: "Docker 활용",
    author: "송지훈",
    content: "Docker 컨테이너 개념.",
    date: "2025-02-26",
    comment: 35,
    views: 115,
  },
  {
    id: 18,
    board: "학업 게시판",
    title: "C 언어 기초",
    author: "이도현",
    content: "C 언어 기본 문법.",
    date: "2025-02-27",
    comment: 9,
    views: 60,
  },
  {
    id: 19,
    board: "취업 게시판",
    title: "IT 트렌드",
    author: "전수진",
    content: "최신 IT 트렌드 소개.",
    date: "2025-02-28",
    comment: 27,
    views: 140,
  },
  {
    id: 20,
    board: "프로젝트 게시판",
    title: "Spring Boot",
    author: "남태현",
    content: `다른곳도 비슷한건지…
이번주에 저는 정말 현업에서 급하다고
금요일까지 내야하는 자료가 있으니, 자료 만드는걸 지원해달라는 요청을 받고 그 요청대로 월 화 수 진행했습니다.
고객사에 제출해야하는거고 금요일까지 제출이니, 수요일안에 해달라고해서 수요일에 딱 맞춰서 다 진행하고 나니…
이번주에 만들기로 했던 기능을 못했는데요 이 기능이 지금 당장 필요한건 아니니 뒤로 미뤘더니 팀장님한테는 제가 뭘하고 있는지 모르겠다.
이런말을 들었는데 너무 현타가 옵니다.
솔직히 지금 생각으로는 오늘 있는 주간 회의때 그걸로 뭐라하면 그냥 때려친다하고 싶은데 다른분들도 비슷하신가요??`,
    date: "2025-03-06",
    comment: 60,
    views: 155,
  },
];

const today = new Date();

const updatedBoardData = openBoardData.map((item) => {
  const postDate = new Date(item.date);
  const diffTime = Math.abs(today - postDate);
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  return {
    ...item,
    title: diffDays <= 3 ? `${item.title} (new)` : item.title,
  };
});

export default updatedBoardData;
