const resourceBoardData = [
  {
    id: 1,
    title: "React 기초",
    lecture: "프론트엔드 개발",
    author: "김철수",
    content: "React의 기본 개념을 설명합니다.",
    date: "2025-02-10",
    views: 100,
  },
  {
    id: 2,
    title: "Node.js 서버",
    lecture: "백엔드 개발",
    author: "이영희",
    content: "Node.js 서버 설정 방법.",
    date: "2025-02-11",
    views: 85,
  },
  {
    id: 3,
    title: "Python 데이터 분석",
    lecture: "데이터 과학",
    author: "박민수",
    content: "판다스를 활용한 데이터 분석.",
    date: "2025-02-12",
    views: 120,
  },
  {
    id: 4,
    title: "HTML & CSS",
    lecture: "웹 기초",
    author: "정하나",
    content: "HTML과 CSS 기본 문법.",
    date: "2025-02-13",
    views: 90,
  },
  {
    id: 5,
    title: "알고리즘 문제 풀이",
    lecture: "자료구조",
    author: "손준호",
    content: "DFS와 BFS를 설명합니다.",
    date: "2025-02-14",
    views: 75,
  },
  {
    id: 6,
    title: "Java 기본",
    lecture: "객체 지향 프로그래밍",
    author: "김영수",
    content: "Java의 기본 개념을 다룹니다.",
    date: "2025-02-15",
    views: 110,
  },
  {
    id: 7,
    title: "데이터베이스 기초",
    lecture: "데이터베이스",
    author: "이진호",
    content: "SQL의 기본 개념.",
    date: "2025-02-16",
    views: 95,
  },
  {
    id: 8,
    title: "Django 웹 개발",
    lecture: "백엔드 개발",
    author: "박지성",
    content: "Django 프레임워크 개요.",
    date: "2025-02-17",
    views: 80,
  },
  {
    id: 9,
    title: "Git 사용법",
    lecture: "협업 도구",
    author: "정윤아",
    content: "Git 기본 사용법.",
    date: "2025-02-18",
    views: 60,
  },
  {
    id: 10,
    title: "운영체제 개념",
    lecture: "컴퓨터 공학",
    author: "박성민",
    content: "운영체제의 기본 개념.",
    date: "2025-02-19",
    views: 85,
  },
  {
    id: 11,
    title: "포트폴리오 작성",
    lecture: "취업 준비",
    author: "최서윤",
    content: "효과적인 포트폴리오 작성법.",
    date: "2025-02-20",
    views: 130,
  },
  {
    id: 12,
    title: "Flask 웹 서비스",
    lecture: "백엔드 개발",
    author: "윤석진",
    content: "Flask 기반 웹 서비스 개발.",
    date: "2025-02-21",
    views: 75,
  },
  {
    id: 13,
    title: "SQL 기본",
    lecture: "데이터베이스",
    author: "정은지",
    content: "SQL 기본 문법.",
    date: "2025-02-22",
    views: 90,
  },
  {
    id: 14,
    title: "컴퓨터 네트워크",
    lecture: "네트워크",
    author: "조민지",
    content: "컴퓨터 네트워크 개념.",
    date: "2025-02-23",
    views: 78,
  },
  {
    id: 15,
    title: "이력서 작성",
    lecture: "취업 준비",
    author: "송지훈",
    content: "이력서 작성 팁.",
    date: "2025-02-24",
    views: 88,
  },
  {
    id: 16,
    title: "Vue.js 시작하기",
    lecture: "프론트엔드 개발",
    author: "김나현",
    content: "Vue.js의 기본 개념.",
    date: "2025-02-25",
    views: 105,
  },
  {
    id: 17,
    title: "Docker 활용",
    lecture: "클라우드",
    author: "이도현",
    content: "Docker 컨테이너 개념.",
    date: "2025-02-26",
    views: 115,
  },
  {
    id: 18,
    title: "C 언어 기초",
    lecture: "프로그래밍 기초",
    author: "전수진",
    content: "C 언어 기본 문법.",
    date: "2025-02-27",
    views: 60,
  },
  {
    id: 19,
    title: "IT 트렌드",
    lecture: "기술 동향",
    author: "남태현",
    content: "최신 IT 트렌드 소개.",
    date: "2025-02-28",
    views: 140,
  },
  {
    id: 20,
    title: "Spring Boot",
    lecture: "백엔드 개발",
    author: "김진우",
    content: "Spring Boot 개념과 활용.",
    date: "2025-02-29",
    views: 155,
  },
];

export default resourceBoardData;
